### ISSUE TITLE
Configuration: keys names

### ISSUE THREAD

**Issue by DobretaAndrzejewic** [petoncle/mousemaster#10]
Hi, I'm still experimenting with Mousemaster, it has it's pros and cons, but after some time I obtained a configuration that is quite effective at one hand and also fastly switchable and quite useful.  Now, I have constant problems with .properties file configuration as I need to insert specific keys names and it's difficult to guess how are certain keys called, like Scroll Lock, Pause Break but also many from the Numpad etc.  Do you maybe have a full "dictionary" of the keys for Mousemaster configuration?

**Comment by petoncle** [comment]
Hello!

Here is the list of keys with special names:
- tab 
- enter 
- leftshift 
- leftctrl 
- leftalt 
- rightshift 
- rightctrl 
- rightalt 
- pause 
- capslock 
- esc 
- space 
- pageup 
- pagedown 
- end 
- home 
- left 
- up 
- right 
- down 
- printscreen 
- insert 
- del 
- break 
- backspace 
- leftwin 
- rightwin 
- menu 
- numpad0 
- numpad1 
- numpad2 
- numpad3 
- numpad4 
- numpad5 
- numpad6 
- numpad7 
- numpad8 
- numpad9 
- numpadmultiply 
- numpadadd 
- numpadsubtract 
- numpaddecimal 
- numpaddivide 
- f1 
- f2 
- f3 
- f4 
- f5 
- f6 
- f7 
- f8 
- f9 
- f10 
- f11 
- f12 
- leftcurlybrace (`{`)
- rightcurlybrace (`}`)
- caret (`^`)
- pipe (`|`)
- underscore (`_`)
- plus (`+`)
- minus (`-`)
- hash (`#`)

**Comment by petoncle** [comment]
Scroll Lock key mapping added in the latest [v43 build](https://github.com/petoncle/mousemaster/releases/). The key name scrolllock can now be used in the config file.

**Comment by petoncle** [comment]
I've documented the key list, which is referenced from [configuration-reference.md](https://github.com/petoncle/mousemaster/blob/main/configuration/configuration-reference.md)
