### ISSUE TITLE
Bug Report: Application Unresponsive When Task Manager Is Focused

### ISSUE THREAD

**Issue by creator-hian** [petoncle/mousemaster#12]
# Bug Report: Application Unresponsive When Task Manager Is Focused

## Description
On Windows 11 Pro (version 24H2), the application becomes unresponsive when the Task Manager has focus. This issue prevents users from accessing the application's core functionalities, significantly impacting the user experience.

## Steps to Reproduce
1. Launch the application
2. Open Task Manager in Windows (`Ctrl + Shift + Esc`).
3. Ensure the Task Manager window is in focus.
4. Observe that the application becomes unresponsive or certain features are disabled.

## Expected Behavior
The application should continue to function normally even when the Task Manager is focused. Users should be able to use the application's features without interruption while interacting with Task Manager.

## Actual Behavior
When the Task Manager is focused, the application does not respond or some of its features are disabled. 

## Environment
- **Operating System:** Windows 11 Pro 24H2
- **Application Version:** v46~48
- **Hardware:**
  - **CPU:** Intel i7-13700KF
  - **RAM:** 64GB
  - **GPU:** NVIDIA RTX 4080

## Logs and Screenshots
![2024-12-16 11 52 53](https://github.com/user-attachments/assets/3ded3c9d-ce27-46e2-bb4f-1f98e4868212)

https://github.com/user-attachments/assets/dc9582b7-3452-4835-9e4c-ed6b44230276

**Comment by petoncle** [comment]
Thanks for the report! I believe the task manager requires mousemaster to be run with admin privileges. ("Run as a administrator"). Can I ask if you are running it as admin?

**Comment by creator-hian** [comment]
I checked and found that “Run as administrator” works fine even when the focus is on the task manager.

https://github.com/user-attachments/assets/3c02acc6-9ba8-4118-bb6c-8e7d11fd7b24
