### ISSUE TITLE
Bug Report: Application Crashes When Entering Screen Mode with Three Monitors Connected

### ISSUE THREAD

**Issue by creator-hian** [petoncle/mousemaster#14]
## Description
When running the application (versions v46~48) on a system with three monitors connected, attempting to enter Screen mode causes the application to unexpectedly terminate. This prevents users from utilizing the Screen mode feature in multi-monitor setups.

## Steps to Reproduce
1. **Connect three monitors** to the system.
2. Ensure the system is running **Windows 11 Pro (version 24H2)**.
3. **Launch the application** (versions v46~48).
4. **Attempt to enter Screen mode**.
5. **Observe** that the application closes unexpectedly.

## Expected Behavior
The application should successfully enter Screen mode without crashing, even when three monitors are connected. Users should be able to utilize all Screen mode features seamlessly in a multi-monitor environment.

## Actual Behavior
Upon attempting to enter Screen mode with three monitors connected, the application crashes and closes unexpectedly. This issue restricts the usage of Screen mode in multi-monitor setups.

## Environment
- **Operating System:** Windows 11 Pro 24H2
- **Application Version:** v46~48
- **Hardware:**
  - **CPU:** Intel i7-13700KF
  - **RAM:** 64GB
  - **GPU:** NVIDIA RTX 4080

## Logs and Screenshots
![2024-12-16 12 12 09](https://github.com/user-attachments/assets/6e6dbada-cdee-442b-a0e7-fc1e2d754f90)

https://github.com/user-attachments/assets/714a2aff-4948-43b5-aff5-c14de97aee7b

**Comment by creator-hian** [comment]
### v48
- HINT MODE only works on monitor 1 (main), and the HINT GRID is not visible on monitor 2.
- On monitor 3, it crashes and exits.


### v45
- I have confirmed that HINT, Screen mode works on all monitors.

**Comment by petoncle** [comment]
I've been trying some fixes for multi-screen hints, it's in [Release 49](https://github.com/petoncle/mousemaster/releases/).

**Comment by creator-hian** [comment]
Currently trying with v51,
and it works fine in all modes.
