### ISSUE TITLE
 How should I configure the grid area in hint mode when Display 1 uses a resolution of 1920x1080 and Display 2 uses 1080x1920?

### ISSUE THREAD

**Issue by creator-hian** [petoncle/mousemaster#16]
I have confirmed that pressing `Shift` in hint mode switches to the `Hint2-1` mode. I adjusted the related property values accordingly.  

However, I would like to control the grid area in hint mode based on the display where the mouse is currently located. What settings should I adjust to achieve this functionality?  

Could you provide guidance on configuring this behavior?

**Comment by petoncle** [comment]
Can you share a screenshot of what it looks like, currently?

**Comment by petoncle** [comment]
Can you try change increase the value of these two lines?
```properties
hint1-mode.hint.grid-max-row-count=26
hint1-mode.hint.grid-max-column-count=26
```
to 100:
```properties
hint1-mode.hint.grid-max-row-count=100
hint1-mode.hint.grid-max-column-count=100
```

**Comment by petoncle** [comment]
I think I will change the default value to 100. I can't think of a reason for it to be 26 now.

**Comment by creator-hian** [comment]
"It is difficult to consider this a bug; it seems to be functioning as intended."

![2024-12-18 19 24 15](https://github.com/user-attachments/assets/13a432cf-2e4c-4f18-b820-8cfa2a50faeb)

**Comment by petoncle** [comment]
@creator-hian Can you try changing:
```properties
hint1-mode.hint.grid-cell-width=73
```
to
```properties
hint1-mode.hint.grid-cell-width=72
```
Does it still require 3 letters on the vertical screen?
