### ISSUE TITLE
The current machine does not support all of the following CPU features that are required by the image

### ISSUE THREAD

**Issue by deadcombo** [petoncle/mousemaster#2]
Hello,

Running the provided binary on an Intel Sandy Bridge CPU, mousemaster.exe returns:
```
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.
```

I understand that I need to build `mousemaster.exe` for my CPU, just a heads up if you're not using all of those.

**Comment by petoncle** [comment]
Thanks for reporting the issue. I think you're right, the exe needs to be rebuilt for that CPU. I believe we may be able to produce an exe that runs properly on Sandy Bridge CPUs using the `march=sandybridge` option documented in the [GraalVM native image docs](https://www.graalvm.org/latest/reference-manual/native-image/overview/Options/). Not sure yet what's the easiest way to do that.

**Comment by deadcombo** [comment]
Hey there, cheers for taking the time! It works!

I ran your binary without a hitch, no complaints in stdout. This is a great improvement on mouseable, thank you for sharing it.

**Comment by petoncle** [comment]
Good to hear! I'm glad it's working for you. I will continue testing this build myself, but I haven't noticed any difference so far. We should be able to make everyone use it.
