### ISSUE TITLE
Move caret

### ISSUE THREAD

**Issue by DRYN07** [petoncle/mousemaster#6]
Is it possible with MouseMaster to move only the caret? I use TouchCursor for it now, but it has not been maintained for a long time. I would be extremely happy if MouseMaster could handle it besides the mouse cursor.

**Comment by petoncle** [comment]
Unfortunately, at this time, no, mousemaster is only for controlling the mouse/cursor. What you are trying to do is called key remapping (the mouse is not involved). I know there are tools that focus on that, like [capsicain](https://github.com/cajhin/capsicain), but I've never tried them.
