### ISSUE TITLE
nice job，do we have custom cursor jump distance config ？

### ISSUE THREAD

**Issue by tlhc** [petoncle/mousemaster#7]

**Comment by petoncle** [comment]
In the recommended config ([neo-mousekeys](https://github.com/petoncle/mousemaster/blob/main/configuration/neo-mousekeys.md)), there is a mode called `jump` that you enable by maintaining the _jump_ key pressed (_j_ by default). Then, when you press a direction key (_w_, _a_, _s_, _d_ by default), the cursor will jump by a quarter of the screen size.

In the config file, this is defined here:
```properties
normal-mode.to.jump-mode=+jump
jump-mode.to.normal-mode=-jump
jump-mode.to.slow-jump-mode=+slow
jump-mode.indicator=normal-mode.indicator
jump-mode.mouse=normal-mode.mouse
jump-mode.stop-move=normal-mode.stop-move
# Invisible grid that is centered around the mouse and has a width and height equal to
# half the screen's width and height.
jump-mode.grid.area=active-screen
jump-mode.grid.area-width-percent=0.5
jump-mode.grid.area-height-percent=0.5
jump-mode.grid.synchronization=grid-center-follows-mouse
# Change line-visible to true to see the edge lines.
jump-mode.grid.line-visible=false
# Jump with direction keys, or by pressing the jump key (if direction keys are already pressed).
jump-mode.snap.up=+up | _{up} +jump
jump-mode.snap.down=+down | _{down} +jump
jump-mode.snap.left=+left | _{left} +jump
jump-mode.snap.right=+right | _{right} +jump
```
where:
- `jump` is a key alias for `j`
- `jump-mode.grid.area-width-percent=0.5` means there will be an invisible rectangle (grid) around the cursor, of width equal to half the screen width
- `jump-mode.snap.left=+left | _{left} +jump` is a command that will snap the cursor to the left edge of the invisible grid when the _left_ key is pressed (_a_ by default), effectively making the cursor jump by a quarter (0.25) of the screen width.

Does that make sense? Is it what you were looking for?

**Comment by tlhc** [comment]
Yes, thanks, according to you suggestion, I change the grid row | col count in normal mode from 1 -> 3, it's jump very smooth 👍

```ini
normal-mode.grid.area-width-percent=1.0
normal-mode.grid.area-height-percent=1.0
# change 1 -> 3
normal-mode.grid.row-count=3
normal-mode.grid.column-count=3
# Require that leftshift remains unpressed,jump 1/3 each step
normal-mode.snap.up=_{leftshift} +k
normal-mode.snap.down=_{leftshift} +j
normal-mode.snap.left=_{leftshift} +h
normal-mode.snap.right=_{leftshift} +l
normal-mode.snap.area-height-percent=1.0
normal-mode.snap.area-width-percent=1.0
normal-mode.snap.grid.area-top-inset=15
normal-mode.move-to-grid-center=_{leftshift} +m
```
